### ISSUE TITLE
Can't load on Fabric server - loads fine on client

### ISSUE THREAD

**Issue by L0rdLogan** [Fusion-Flux/Supernatural-Crops#1] opened 2020-12-28 18:25 UTC
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supernaturalcrops'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/blockrenderlayer/v1/BlockRenderLayerMap
        at com.fusionflux.supernaturalcrops.blocks.SupernaturalCropsBlocks.registerBlocks(SupernaturalCropsBlocks.java:35) ~[supernatural-crops-1.0.2.jar:?]
        at com.fusionflux.supernaturalcrops.SupernaturalCrops.onInitialize(SupernaturalCrops.java:37) ~[supernatural-crops-1.0.2.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at com.fusionflux.supernaturalcrops.blocks.SupernaturalCropsBlocks.registerBlocks(SupernaturalCropsBlocks.java:35) ~[supernatural-crops-1.0.2.jar:?]
        at com.fusionflux.supernaturalcrops.SupernaturalCrops.onInitialize(SupernaturalCrops.java:37) ~[supernatural-crops-1.0.2.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more

Fabric version: 10.8
Fabric API version: fabric-api-0.28.4+1.16

**Comment by Fusion-Flux** [comment] 2020-12-29 18:34
Found out bug was caused by client renderers trying to be used in the server causing a crash bug was fixed in the latest update. Thanks for reporting this issue!

**Closed as completed by Fusion-Flux** 2020-12-29 18:34 UTC
